version: '3.3'
services:
  tyk-gateway:
    image: docker.tyk.io/tyk-gateway/tyk-gateway:v3.1.2
    environment:
      - TYK_GW_POLICIES_POLICYSOURCE=rpc
      - TYK_GW_POLICIES_POLICYRECORDNAME=tyk_policies
      - TYK_GW_USEDBAPPCONFIGS=False
      - TYK_GW_ANALYTICSCONFIG_TYPE=rpc
    ports:
      - 8080:8080
    networks:
      - tyk
    volumes:
      - ./tyk.hybrid.conf:/opt/tyk-gateway/tyk.conf
      - ./apps:/opt/tyk-gateway/apps
      - ./middleware:/opt/tyk-gateway/middleware
      - ./certs:/opt/tyk-gateway/certs
    environment:
      - TYK_GW_SECRET=foo
    depends_on:
      - tyk-redis
  tyk-redis:
    image: redis:5.0-alpine
    networks:
      - tyk
    ports:
      - 6379:6379
  tyk-pump:
    image: tykio/tyk-pump-docker-pub:v1.5.1-rc5
    environment:
      - TYK_PMP_PUMPS_PROMETHEUS_TYPE=prometheus
      - TYK_PMP_PUMPS_PROMETHEUS_META_ADDR=0.0.0.0:9191
      - TYK_PMP_PUMPS_PROMETHEUS_META_PATH=/metrics
      - TYK_PMP_ANALYTICSSTORAGETYPE=redis
      - TYK_PMP_ANALYTICSSTORAGECONFIG_HOST=tyk-redis
      - TYK_PMP_ANALYTICSSTORAGECONFIG_PORT=6379
      - TYK_PMP_OMITCONFIGFILE=true
      - TYK_PMP_DONTPURGEUPTIMEDATA=true
      - TYK_PMP_PURGEDELAY=2
    ports:
      - "9191:9191"
    networks:
      - tyk
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus

    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-admin-api

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - tyk

networks:
  tyk:
